Impurity: added detailed bath parameters and a python script to retri…
varbench/varbench pull request #8
Opened 2024-02-29 08:20 UTC by xiaodongcao

…ve the data

2024-02-29 08:30 UTC, gcarleo requested changes

2024-02-29 08:30 UTC, gcarleo commented on Impurity/README.md
> +The impurity Hamitonian parameters are store in `HamParams` folder. The names of the Hamiltonian follow the same convention of `model_Nb.h5`. The following example python script describes their data
```suggestion
The impurity Hamitonian parameters are stored in `HamParams` folder. The names of the Hamiltonian follow the same convention of `model_Nb.h5`. The following example python script describes their data structure
```

2024-03-12 11:04 UTC, PhilipVinc approved these changes

2024-03-12 11:04 UTC, PhilipVinc commented
@gcarleo can you merge?

2024-03-12 12:13 UTC, gcarleo approved these changes

2024-03-12 12:14 UTC, merged